<?php return array(
    'root' => array(
        'name' => 'wpdesk/woocommerce-fakturownia',
        'pretty_version' => '1.10.6',
        'version' => '1.10.6.0',
        'reference' => 'f3b27e7b8aca34b7cced6dae7bdeb4a53db86b61',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wpdesk/woocommerce-fakturownia' => array(
            'pretty_version' => '1.10.6',
            'version' => '1.10.6.0',
            'reference' => 'f3b27e7b8aca34b7cced6dae7bdeb4a53db86b61',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wpdesk/wp-wpdesk-helper-override' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '77844fc71da7ebb7645f10f0fc15f5294fed8542',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wpdesk/wp-wpdesk-helper-override',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
